import path from 'node:path'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

function writeFirebaseSwConfig(env) {
  const config = {
    apiKey: env.VITE_FIREBASE_API_KEY || '',
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN || '',
    projectId: env.VITE_FIREBASE_PROJECT_ID || '',
    storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET || '',
    messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
    appId: env.VITE_FIREBASE_APP_ID || '',
  }
  const contents = `// Generated by Vite — do not edit. Matches VITE_FIREBASE_* in .env
self.FIREBASE_SW_CONFIG = ${JSON.stringify(config, null, 2)};
`
  writeFileSync(path.resolve(__dirname, 'public/firebase-sw-config.js'), contents)
}

function firebaseSwConfigPlugin(env) {
  return {
    name: 'firebase-sw-config',
    buildStart() {
      writeFirebaseSwConfig(env)
    },
    configureServer(server) {
      writeFirebaseSwConfig(env)
      server.watcher.on('change', (file) => {
        if (file.includes('.env')) writeFirebaseSwConfig(loadEnv(server.config.mode, process.cwd(), ''))
      })
    },
  }
}

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  /** Local Dev-co default (see Dev-co/.env PORT). Override in .env.development. */
  const apiProxyTarget =
    env.VITE_API_PROXY_TARGET || 'http://localhost:4000'

  return {
    plugins: [firebaseSwConfigPlugin(env), react(), tailwindcss()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, 'src'),
      },
    },
    server: {
      proxy: {
        // Browser → localhost:5173/api/v1/... → Vite proxies to local Dev-co (or override).
        '/api': {
          target: apiProxyTarget,
          changeOrigin: true,
          secure: false,
        },
        '/uploads': {
          target: apiProxyTarget,
          changeOrigin: true,
          secure: false,
        },
        '/socket.io': {
          target: apiProxyTarget,
          changeOrigin: true,
          ws: true,
        },
      },
    },
  }
})
