/** Mirrors mobile `shared/theme/auth.ts`. */
export const authColors = {
  gradientStart: "#E4ECFF",
  gradientMid: "#EEF2FF",
  gradientEnd: "#FFFFFF",
  navy: "#0F172A",
  navySoft: "#1E293B",
  textMuted: "#64748B",
  textLight: "#94A3B8",
  indigo: "#5B6CFF",
  indigoPressed: "#4F5EE6",
  badgeBg: "#EFF6FF",
  badgeBorder: "#BFDBFE",
  badgeText: "#3730A3",
  cardBg: "#FFFFFF",
  cardBorder: "#E2E8F0",
  inputBg: "#F8FAFC",
  inputBorder: "#E2E8F0",
  inputText: "#0F172A",
  iconBlue: "#3B82F6",
  iconBlueBg: "#DBEAFE",
  error: "#EF4444",
  white: "#FFFFFF",
};
